name: dashboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.3
  google_maps_flutter_web: ^0.3.2+1
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.6
  intl: ^0.17.0
  location: ^4.3.0
  mask_text_input_formatter: ^2.3.0
  responsive_framework: ^0.1.7
  rxdart: ^0.27.3
  simple_animations: ^4.0.1
  universal_html: ^2.0.8
  validators: ^3.0.0

dev_dependencies:
  bloc_test: ^9.0.3
  faker: ^2.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2
  mocktail: ^0.3.0
  network_image_mock: ^2.1.0
  test: ^1.19.5

flutter:
  uses-material-design: true

  assets:
    - assets/
