name: dashboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.8
  google_fonts: ^2.2.0
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2+1
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker: ^0.8.4+5
  image_picker_for_web: ^2.1.5
  intl: ^0.17.0
  location: ^4.3.0
  mask_text_input_formatter: ^2.1.0
  meta: ^1.7.0
  responsive_framework: ^0.1.5
  rxdart: ^0.27.3
  simple_animations: ^4.0.1
  universal_html: ^2.0.8

dev_dependencies:
  bloc_test: ^9.0.2
  faker: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2
  mocktail: ^0.2.0
  network_image_mock: ^2.0.1
  test: ^1.17.12

flutter:
  uses-material-design: true

  assets:
    - assets/
